apiVersion: v2
appVersion: "1.5.0"
version: 10.0.16
kubeVersion: ">=1.16.0-0"
name: shiori
description: A simple bookmark manager built with Go
type: application
home: https://truecharts.org/charts/stable/shiori
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shiori.png
keywords:
  - shiori
  - bookmark
  - bookmark-manager
  - web-interface
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/shiori
  - https://github.com/go-shiori/shiori
  - https://github.com/nicholaswilde/docker-shiori
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.18
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
