image:
  repository: ghcr.io/go-shiori/shiori
  pullPolicy: IfNotPresent
  tag: v1.5.3@sha256:18dd8f354d6f23919c55ed7e63b85747659dad81173766146e81dd051b71c0df

securityContext:
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  SHIORI_PG_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  SHIORI_PG_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  SHIORI_PG_PASS:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  SHIORI_PG_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

service:
  main:
    ports:
      main:
        port: 10098
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: shiori
  postgresqlDatabase: shiori

portal:
  enabled: true
